install:
	cp weather-cli.sh /usr/local/bin/weather-cli
	chmod +rx /usr/local/bin/weather-cli
	cp bash_completion.d/weather-cli /etc/bash_completion.d/weather-cli

uninstall:
	rm /etc/bash_completion.d/weather-cli
	rm /usr/local/bin/weather-cli

